Pull changes from centos image at https://github.com/sclorg/rhscl-dockerfiles

diff --git a/mariadb/test/run b/mariadb/test/run
--- a/mariadb/test/run
+++ b/mariadb/test/run
@@ -9,7 +9,7 @@
 set -exo nounset
 shopt -s nullglob
 
-IMAGE_NAME=${IMAGE_NAME-fedora/mariadb}
+IMAGE_NAME=${IMAGE_NAME-centos/mariadb-100-centos7-candidate}
 
 CIDFILE_DIR=$(mktemp --suffix=mysql_test_cidfiles -d)
 
@@ -145,6 +145,29 @@ function run_replication_test() {
     fi
     sleep 1
   done
+
+  # do some real work to test replication in practice
+  CONTAINER_IP=${master_ip} USER=root PASS=root \
+    mysql_cmd -e "CREATE TABLE t1 (a INT); INSERT INTO t1 VALUES (24);"
+
+  # read value from slave and check whether it is expectd
+  for i in $(seq $max_attempts); do
+    set +e
+    result=$(CONTAINER_IP=${slave_ip} USER=root PASS=root \
+      mysql_cmd -e "select * from t1 \G" | grep -e ^a | grep 24)
+    set -e
+    if [[ ! -z "${result}" ]]; then
+      echo "${slave_ip} successfully got value from MASTER ${master_ip}"
+      break
+    fi
+    if [[ "${i}" == "${max_attempts}" ]]; then
+      echo "The ${slave_ip} failed to see value added on MASTER"
+      echo "Dumping logs for $(get_cid slave.cid)"
+      docker logs $(get_cid slave.cid)
+      return 1
+    fi
+    sleep 1
+  done
 }
 
 function assert_login_access() {
@@ -262,6 +285,8 @@ function run_tests() {
   create_container $name $envs
   CONTAINER_IP=$(get_container_ip $name)
   test_connection $name
+  echo "  Testing scl usage"
+  test_scl_usage $name 'mysql --version' '10.0'
   echo "  Testing login accesses"
   assert_login_access $USER $PASS true
   assert_login_access $USER "${PASS}_foo" false
@@ -287,7 +312,7 @@ run_container_creation_tests
 # run_configuration_tests
 
 # Set lower buffer pool size to avoid running out of memory.
-export CONTAINER_ARGS="mysqld --innodb_buffer_pool_size=5242880"
+export CONTAINER_ARGS="run-mysqld --innodb_buffer_pool_size=5242880"
 
 # Normal tests
 USER=user PASS=pass run_tests no_root
